<?php


/**
 * Implements hook_menu().
 */
function rend_mod_menu() {
  $items['simple_page'] = array(
    'title' => 'Simple page',
    'page callback' => 'rend_simple_page_content',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'file' => 'rend_mod.pages.inc',
    'options' => array('attributes' => array('class' => array('test-class'))),
  );



  $items['simple_page/sub-user-stas'] = array(
    'title' => 'Simple page stas',
    'page callback' => 'rend_simple_page_user_stas',
    'file' => 'rend_mod.pages.inc',
    'access callback' => TRUE,
    'expanded' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_LOCAL_TASK,
  );


    $items['simple_page/sub-user-list'] = array(
    'title' => 'Simple page list123',
    'page callback' => 'rend_simple_page_user_list',
    'access callback' => TRUE,
    'expanded' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_LOCAL_TASK,
  );

    $items['simple_page/Form-page'] = array(
      'title' => 'Example Form',
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('access content'),
      'page callback' => 'drupal_get_form',
      'page arguments'=>array('rend_mod_form'),
      'menu_name' => 'main-menu',
      'access callback' => TRUE,
      'expanded' => TRUE,

    );

  return $items;

}

/**
 * Implements hook_theme().
 */
function rend_mod_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['rend_list_items'] = array(
    'render element' => 'list',
    'path' => drupal_get_path('module', 'rend_mod') . '/templates',
    'template' => 'block-rend-mod-custom-list',
  );

  $items['rend_list_items_2'] =array(
    'variables' => array('message' => NULL),
    'path' => drupal_get_path('module', 'rend_mod') . '/templates' ,
    'template' => 'block-rend-mod-custom-list-2',

  );





  return $items;
}

function rend_simple_page_user_list() {
  $mess_user = t('list user site');
  $mess_root = t('list root site');


  $content = array(
    '#theme' => 'rend_list_items',

    'mess_user' => array(
      '#message' => $mess_user,
      '#theme' => 'rend_list_items_2',
    ),

    'mess_root' => array(
      '#message' => $mess_root,
      '#theme' => 'create_node_form',
    ),
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'rend_mod') . '/css/styles.css',
      ),
    ),
  );

 $content['form'] = drupal_get_form('rend_mod_form');

  return $content;
}

/**
 * Implements hook_block_view().
 */
function rend_mod_block_view($delta = '') {
  $block = array();

  $block['content'] = drupal_get_form('rend_mod_form');

  return $block;
}


/**
 * Implements hook_form().
 */
function rend_mod_form($node, &$form_state) {

  $form = array();


  $form['name']=array(
    '#type'=>'textfield',
    '#title'=>t('Enter your name'),
    '#description'=>t('Your first name goes here'),
  );
  $form['last_name']=array(
    '#type'=>'textfield',
    '#title'=>t('Enter your Last name'),
    '#description'=>t('Your Last name goes here'),
  );

  $form['email']=array(
    '#type'=>'textfield',
    '#title'=>t('Enter your email'),
    '#description'=>t('Your email goes here'),
  );

  $form['country']=array(
    '#type'=>'select',
    '#title'=>t('Select your country'),
    '#options'=>array('USA','UK','France', 'EN'),
  );


  $form['birthdate'] = array(
    '#title' => t('birthdate'),
    '#type' => 'date',
    '#description' => t('Select your birthdate'),
  '#value' => array(
    'month' => format_date(time(), 'custom', 'n'),
    'day' => format_date(time(), 'custom', 'j'),
    'year' => format_date(time(), 'custom', 'Y'),
  ),
  );

    $form['submit']['default']=array(
    '#type'=>'submit',
    '#value'=>t('Submit'),
    '#weight' => 12,
     );

  $form['submit']['custom']=array(
    '#type'=>'submit',
    '#value'=>t('Submit custom'),
    '#weight' => 1,
    '#submit' => array('rend_mod_form_submit_custom'),

  );


  return $form;
}


function rend_mod_form_validate($form, &$form_state) {

  if (empty($form_state['values']['name']))
    form_set_error('name', 'Name cannot be empty');
  else if(empty($form_state['values']['last_name']))
    form_set_error('last_name', 'Last name cannot be empty' );
  else if(filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL) == false)
    form_set_error('email', 'Email is not valid');
  if ($form_state['values']['birthdate']['year'] < '1930') {
    form_set_error('year', t('youre too old'));
  } else if ($form_state['values']['birthdate']['year'] > '2010') {
    form_set_error('year', t('you are too young'));
  }
}

function rend_mod_form_submit($form, &$form_state) {
  drupal_set_message('Form is submitted classic');
}

function rend_mod_form_submit_custome() {
  drupal_set_message('Form ok validate');
}










